BigData:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark-master
      port: 10000
      user: spark
      schema: default
      threads: 4
      connect_timeout: 10